version: '3.8'

networks:
  reverse_proxy:
    external: true

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - /etc/nginx/conf.d
    networks:
      - reverse_proxy

  dockergen:
    image: nginxproxy/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl
      /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    networks:
      - reverse_proxy

  whoami:
    image: jwilder/whoami
    expose:
      - 7000
    environment:
      - PORT=7000
      - VIRTUAL_HOST=whoami.clubs.iiit.ac.in
      - VIRTUAL_PORT=7000
    networks:
      - reverse_proxy
