version: "3.8"

volumes:
  certs:
  vhost:
  html:
  acme:

networks:
  reverse_proxy:
    external: true

services:
  nginx:
    image: nginxproxy/nginx-proxy:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx:/etc/nginx/conf.d
      - /etc/ssl:/etc/ssl:ro
    networks:
      - reverse_proxy
    restart: unless-stopped

  acme:
    image: nginxproxy/acme-companion
    volumes_from:
      - nginx
    volumes:
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - ./.env
    networks:
      - reverse_proxy
    restart: unless-stopped
